// Generated by typings
// Source: https://raw.githubusercontent.com/meteor-typings/angular2-compilers/c2ca3d3036b08f04a22b98ed16ff17377499e1e7/main.d.ts
declare module "*.html" {
  const template: string;
  export default template;
}

declare module "*.less" {
  const template: string;
  export default template;
}

declare module "*.sass" {
  const template: string;
  export default template;
}

declare module "*.scss" {
  const template: string;
  export default template;
}
